### ISSUE TITLE
PRIORIDADE - Manter Login

### ISSUE THREAD

**Issue by willian-campos-incript** [AndersonAlvesCoelho/linkedin-connection#7]
Quando o script "Quebrar" ou "Crashar" não ter a necessidade de realizar login, apenas ser redirecionado para home e mostrar novamente a opções do menu

**Comment by AndersonAlvesCoelho** [comment]
Vou está mapeando o projeto todo para e trata todas as exceçõesque que pode acontece por causa que o puppeteer nao encontra o elemento da DOM. 
Vou está mexendo nisso. 
@willian-campos-incript @raphael-rissoli-incript
